# Configure Using Gemfile
# gem 'pg'
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: oldnews_development


test:
  <<: *default
  database: oldnews_test


production:
  <<: *default
  database: oldnews_production
  username: oldnews
  password: <%= ENV['OLDNEWS_DATABASE_PASSWORD'] %>
